import { jsPDF } from "jspdf";

export const generatePDFReport = (profile: any, history: any[]) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("RehabIris Medical Report", 20, 25);
  
  // Patient Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text(`Patient Name: ${profile.name}`, 20, 55);
  doc.text(`Age: ${profile.age}`, 20, 65);
  doc.text(`Injury Type: ${profile.injuryType}`, 20, 75);
  doc.text(`Injury Area: ${profile.injuryArea || 'N/A'}`, 20, 85);
  
  // Analysis
  doc.setFontSize(16);
  doc.text("AI Recovery Analysis", 20, 105);
  doc.setFontSize(12);
  const splitExplanation = doc.splitTextToSize(profile.explanation || "No explanation provided.", 170);
  doc.text(splitExplanation, 20, 115);
  
  // Performance
  doc.setFontSize(16);
  doc.text("Exercise Performance Summary", 20, 150);
  doc.setFontSize(10);
  let y = 160;
  doc.text("Date", 20, y);
  doc.text("Exercise", 70, y);
  doc.text("Reps", 130, y);
  doc.text("Accuracy", 160, y);
  
  doc.line(20, y + 2, 190, y + 2);
  y += 10;
  
  history.slice(-10).forEach(h => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(new Date(h.date).toLocaleDateString(), 20, y);
    doc.text(h.exercise, 70, y);
    doc.text(h.reps.toString(), 130, y);
    doc.text(`${h.accuracy}%`, 160, y);
    y += 8;
  });

  // Recovery Journey Page
  doc.addPage();
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("Recovery Journey Map", 20, 20);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text("Recovery Stages", 20, 50);

  const stages = [
    { level: "Level 1", desc: "Initial Mobility & Pain Management", status: "Completed" },
    { level: "Level 2", desc: "Strength Building & Stability", status: "In Progress" },
    { level: "Level 3", desc: "Functional Movement & Endurance", status: "Upcoming" },
    { level: "Level 4", desc: "Full Return to Activity", status: "Upcoming" }
  ];

  let stageY = 65;
  stages.forEach((s, i) => {
    doc.setFillColor(i === 1 ? 79 : 240, i === 1 ? 70 : 240, i === 1 ? 229 : 240);
    doc.roundedRect(20, stageY, 170, 25, 3, 3, 'F');
    doc.setTextColor(i === 1 ? 255 : 100, i === 1 ? 255 : 100, i === 1 ? 255 : 100);
    doc.setFontSize(12);
    doc.text(`${s.level}: ${s.desc}`, 30, stageY + 10);
    doc.setFontSize(10);
    doc.text(`Status: ${s.status}`, 30, stageY + 18);
    stageY += 30;
  });

  // Progress Visualization
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text("Current Recovery Progress", 20, 200);
  
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(20, 210, 170, 10, 5, 5, 'F');
  doc.setFillColor(79, 70, 229);
  doc.roundedRect(20, 210, 170 * 0.65, 10, 5, 5, 'F'); // 65% progress
  
  doc.setFontSize(12);
  doc.text("65% Recovered", 20, 230);
  doc.text("Estimated Completion: 14 Days", 20, 240);
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by RehabIris AI Tele-Rehabilitation System", 105, 290, { align: 'center' });
  
  doc.save(`RehabIris_Report_${profile.name}.pdf`);
};
